// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.MicrosoftGraph.Users.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MicrosoftgraphbaseItem : Microsoftgraphentity
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphbaseItem class.
        /// </summary>
        public MicrosoftgraphbaseItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphbaseItem class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">Read-only.</param>
        /// <param name="createdDateTime">Date and time of item creation.
        /// Read-only.</param>
        /// <param name="description">Provides a user-visible description of
        /// the item. Optional.</param>
        /// <param name="eTag">ETag for the item. Read-only.</param>
        /// <param name="lastModifiedDateTime">Date and time the item was last
        /// modified. Read-only.</param>
        /// <param name="name">The name of the item. Read-write.</param>
        /// <param name="webUrl">URL that displays the resource in the browser.
        /// Read-only.</param>
        public MicrosoftgraphbaseItem(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string id = default(string), Microsoftgraphuser createdByUser = default(Microsoftgraphuser), System.DateTime? createdDateTime = default(System.DateTime?), string description = default(string), string eTag = default(string), Microsoftgraphuser lastModifiedByUser = default(Microsoftgraphuser), System.DateTime? lastModifiedDateTime = default(System.DateTime?), string name = default(string), string webUrl = default(string))
            : base(additionalProperties, id)
        {
            CreatedByUser = createdByUser;
            CreatedDateTime = createdDateTime;
            Description = description;
            ETag = eTag;
            LastModifiedByUser = lastModifiedByUser;
            LastModifiedDateTime = lastModifiedDateTime;
            Name = name;
            WebUrl = webUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdByUser")]
        public Microsoftgraphuser CreatedByUser { get; set; }

        /// <summary>
        /// Gets or sets date and time of item creation. Read-only.
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public System.DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// Gets or sets provides a user-visible description of the item.
        /// Optional.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets eTag for the item. Read-only.
        /// </summary>
        [JsonProperty(PropertyName = "eTag")]
        public string ETag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastModifiedByUser")]
        public Microsoftgraphuser LastModifiedByUser { get; set; }

        /// <summary>
        /// Gets or sets date and time the item was last modified. Read-only.
        /// </summary>
        [JsonProperty(PropertyName = "lastModifiedDateTime")]
        public System.DateTime? LastModifiedDateTime { get; set; }

        /// <summary>
        /// Gets or sets the name of the item. Read-write.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets URL that displays the resource in the browser.
        /// Read-only.
        /// </summary>
        [JsonProperty(PropertyName = "webUrl")]
        public string WebUrl { get; set; }

    }
}
