// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for MdmAuthority.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MdmAuthority
    {
        /// <summary>
        /// Unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,
        /// <summary>
        /// Intune
        /// </summary>
        [EnumMember(Value = "intune")]
        Intune,
        /// <summary>
        /// SCCM
        /// </summary>
        [EnumMember(Value = "sccm")]
        Sccm,
        /// <summary>
        /// Office365
        /// </summary>
        [EnumMember(Value = "office365")]
        Office365
    }
    internal static class MdmAuthorityEnumExtension
    {
        internal static string ToSerializedValue(this MdmAuthority? value)
        {
            return value == null ? null : ((MdmAuthority)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this MdmAuthority value)
        {
            switch( value )
            {
                case MdmAuthority.Unknown:
                    return "unknown";
                case MdmAuthority.Intune:
                    return "intune";
                case MdmAuthority.Sccm:
                    return "sccm";
                case MdmAuthority.Office365:
                    return "office365";
            }
            return null;
        }

        internal static MdmAuthority? ParseMdmAuthority(this string value)
        {
            switch( value )
            {
                case "unknown":
                    return MdmAuthority.Unknown;
                case "intune":
                    return MdmAuthority.Intune;
                case "sccm":
                    return MdmAuthority.Sccm;
                case "office365":
                    return MdmAuthority.Office365;
            }
            return null;
        }
    }
}
