// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Microsoftgraphdirectory : Microsoftgraphentity
    {
        /// <summary>
        /// Initializes a new instance of the Microsoftgraphdirectory class.
        /// </summary>
        public Microsoftgraphdirectory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Microsoftgraphdirectory class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">The unique idenfier for an entity.
        /// Read-only.</param>
        /// <param name="administrativeUnits">Conceptual container for user and
        /// group directory objects.</param>
        /// <param name="deletedItems">Recently deleted items. Read-only.
        /// Nullable.</param>
        /// <param name="federationConfigurations">Configure domain federation
        /// with organizations whose identity provider (IdP) supports either
        /// the SAML or WS-Fed protocol.</param>
        public Microsoftgraphdirectory(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string id = default(string), IList<MicrosoftgraphadministrativeUnit> administrativeUnits = default(IList<MicrosoftgraphadministrativeUnit>), IList<MicrosoftgraphdirectoryObject> deletedItems = default(IList<MicrosoftgraphdirectoryObject>), IList<MicrosoftgraphidentityProviderBase> federationConfigurations = default(IList<MicrosoftgraphidentityProviderBase>))
            : base(additionalProperties, id)
        {
            AdministrativeUnits = administrativeUnits;
            DeletedItems = deletedItems;
            FederationConfigurations = federationConfigurations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets conceptual container for user and group directory
        /// objects.
        /// </summary>
        [JsonProperty(PropertyName = "administrativeUnits")]
        public IList<MicrosoftgraphadministrativeUnit> AdministrativeUnits { get; set; }

        /// <summary>
        /// Gets or sets recently deleted items. Read-only. Nullable.
        /// </summary>
        [JsonProperty(PropertyName = "deletedItems")]
        public IList<MicrosoftgraphdirectoryObject> DeletedItems { get; set; }

        /// <summary>
        /// Gets or sets configure domain federation with organizations whose
        /// identity provider (IdP) supports either the SAML or WS-Fed
        /// protocol.
        /// </summary>
        [JsonProperty(PropertyName = "federationConfigurations")]
        public IList<MicrosoftgraphidentityProviderBase> FederationConfigurations { get; set; }

    }
}
