// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MicrosoftgraphscopedRoleMembership : Microsoftgraphentity
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphscopedRoleMembership class.
        /// </summary>
        public MicrosoftgraphscopedRoleMembership()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphscopedRoleMembership class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">The unique idenfier for an entity.
        /// Read-only.</param>
        /// <param name="administrativeUnitId">Unique identifier for the
        /// administrative unit that the directory role is scoped to</param>
        /// <param name="roleId">Unique identifier for the directory role that
        /// the member is in.</param>
        public MicrosoftgraphscopedRoleMembership(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string id = default(string), string administrativeUnitId = default(string), string roleId = default(string), Microsoftgraphidentity roleMemberInfo = default(Microsoftgraphidentity))
            : base(additionalProperties, id)
        {
            AdministrativeUnitId = administrativeUnitId;
            RoleId = roleId;
            RoleMemberInfo = roleMemberInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unique identifier for the administrative unit that the
        /// directory role is scoped to
        /// </summary>
        [JsonProperty(PropertyName = "administrativeUnitId")]
        public string AdministrativeUnitId { get; set; }

        /// <summary>
        /// Gets or sets unique identifier for the directory role that the
        /// member is in.
        /// </summary>
        [JsonProperty(PropertyName = "roleId")]
        public string RoleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roleMemberInfo")]
        public Microsoftgraphidentity RoleMemberInfo { get; set; }

    }
}
