// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MicrosoftgraphdomainDnsRecord : Microsoftgraphentity
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphdomainDnsRecord
        /// class.
        /// </summary>
        public MicrosoftgraphdomainDnsRecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphdomainDnsRecord
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">The unique idenfier for an entity.
        /// Read-only.</param>
        /// <param name="isOptional">If false, this record must be configured
        /// by the customer at the DNS host for Microsoft Online Services to
        /// operate correctly with the domain.</param>
        /// <param name="label">Value used when configuring the name of the DNS
        /// record at the DNS host.</param>
        /// <param name="recordType">Indicates what type of DNS record this
        /// entity represents.The value can be one of the following: CName, Mx,
        /// Srv, Txt.</param>
        /// <param name="supportedService">Microsoft Online Service or feature
        /// that has a dependency on this DNS record.Can be one of the
        /// following values: null, Email, Sharepoint, EmailInternalRelayOnly,
        /// OfficeCommunicationsOnline, SharePointDefaultDomain,
        /// FullRedelegation, SharePointPublic, OrgIdAuthentication, Yammer,
        /// Intune.</param>
        /// <param name="ttl">Value to use when configuring the time-to-live
        /// (ttl) property of the DNS record at the DNS host. Not
        /// nullable.</param>
        public MicrosoftgraphdomainDnsRecord(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string id = default(string), bool? isOptional = default(bool?), string label = default(string), string recordType = default(string), string supportedService = default(string), int? ttl = default(int?))
            : base(additionalProperties, id)
        {
            IsOptional = isOptional;
            Label = label;
            RecordType = recordType;
            SupportedService = supportedService;
            Ttl = ttl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets if false, this record must be configured by the
        /// customer at the DNS host for Microsoft Online Services to operate
        /// correctly with the domain.
        /// </summary>
        [JsonProperty(PropertyName = "isOptional")]
        public bool? IsOptional { get; set; }

        /// <summary>
        /// Gets or sets value used when configuring the name of the DNS record
        /// at the DNS host.
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or sets indicates what type of DNS record this entity
        /// represents.The value can be one of the following: CName, Mx, Srv,
        /// Txt.
        /// </summary>
        [JsonProperty(PropertyName = "recordType")]
        public string RecordType { get; set; }

        /// <summary>
        /// Gets or sets microsoft Online Service or feature that has a
        /// dependency on this DNS record.Can be one of the following values:
        /// null, Email, Sharepoint, EmailInternalRelayOnly,
        /// OfficeCommunicationsOnline, SharePointDefaultDomain,
        /// FullRedelegation, SharePointPublic, OrgIdAuthentication, Yammer,
        /// Intune.
        /// </summary>
        [JsonProperty(PropertyName = "supportedService")]
        public string SupportedService { get; set; }

        /// <summary>
        /// Gets or sets value to use when configuring the time-to-live (ttl)
        /// property of the DNS record at the DNS host. Not nullable.
        /// </summary>
        [JsonProperty(PropertyName = "ttl")]
        public int? Ttl { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Ttl > 2147483647)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "Ttl", 2147483647);
            }
            if (Ttl < -2147483648)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Ttl", -2147483648);
            }
        }
    }
}
