// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Microsoftgraphcontract : MicrosoftgraphdirectoryObject
    {
        /// <summary>
        /// Initializes a new instance of the Microsoftgraphcontract class.
        /// </summary>
        public Microsoftgraphcontract()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Microsoftgraphcontract class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">The unique idenfier for an entity.
        /// Read-only.</param>
        /// <param name="deletedDateTime">Date and time when this object was
        /// deleted. Always null when the object hasn't been deleted.</param>
        /// <param name="contractType">Type of contract. Possible values are:
        /// SyndicationPartner, BreadthPartner, ResellerPartner. See more in
        /// the table below.</param>
        /// <param name="customerId">The unique identifier for the customer
        /// tenant referenced by this partnership. Corresponds to the id
        /// property of the customer tenant's organization resource.</param>
        /// <param name="defaultDomainName">A copy of the customer tenant's
        /// default domain name. The copy is made when the partnership with the
        /// customer is established. It is not automatically updated if the
        /// customer tenant's default domain name changes.</param>
        /// <param name="displayName">A copy of the customer tenant's display
        /// name. The copy is made when the partnership with the customer is
        /// established. It is not automatically updated if the customer
        /// tenant's display name changes.</param>
        public Microsoftgraphcontract(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string id = default(string), System.DateTime? deletedDateTime = default(System.DateTime?), string contractType = default(string), System.Guid? customerId = default(System.Guid?), string defaultDomainName = default(string), string displayName = default(string))
            : base(additionalProperties, id, deletedDateTime)
        {
            ContractType = contractType;
            CustomerId = customerId;
            DefaultDomainName = defaultDomainName;
            DisplayName = displayName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets type of contract. Possible values are:
        /// SyndicationPartner, BreadthPartner, ResellerPartner. See more in
        /// the table below.
        /// </summary>
        [JsonProperty(PropertyName = "contractType")]
        public string ContractType { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the customer tenant
        /// referenced by this partnership. Corresponds to the id property of
        /// the customer tenant's organization resource.
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// Gets or sets a copy of the customer tenant's default domain name.
        /// The copy is made when the partnership with the customer is
        /// established. It is not automatically updated if the customer
        /// tenant's default domain name changes.
        /// </summary>
        [JsonProperty(PropertyName = "defaultDomainName")]
        public string DefaultDomainName { get; set; }

        /// <summary>
        /// Gets or sets a copy of the customer tenant's display name. The copy
        /// is made when the partnership with the customer is established. It
        /// is not automatically updated if the customer tenant's display name
        /// changes.
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }
    }
}
