// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// phone
    /// </summary>
    public partial class Microsoftgraphphone
    {
        /// <summary>
        /// Initializes a new instance of the Microsoftgraphphone class.
        /// </summary>
        public Microsoftgraphphone()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Microsoftgraphphone class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="number">The phone number.</param>
        /// <param name="type">Possible values include: 'home', 'business',
        /// 'mobile', 'other', 'assistant', 'homeFax', 'businessFax',
        /// 'otherFax', 'pager', 'radio'</param>
        public Microsoftgraphphone(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string language = default(string), string number = default(string), string region = default(string), string type = default(string))
        {
            AdditionalProperties = additionalProperties;
            Language = language;
            Number = number;
            Region = region;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// Gets or sets the phone number.
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "region")]
        public string Region { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'home', 'business', 'mobile',
        /// 'other', 'assistant', 'homeFax', 'businessFax', 'otherFax',
        /// 'pager', 'radio'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
