// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// privacyProfile
    /// </summary>
    public partial class MicrosoftgraphprivacyProfile
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphprivacyProfile
        /// class.
        /// </summary>
        public MicrosoftgraphprivacyProfile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphprivacyProfile
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="contactEmail">A valid smtp email address for the
        /// privacy statement contact. Not required.</param>
        /// <param name="statementUrl">A valid URL format that begins with
        /// http:// or https://. Maximum length is 255 characters. The URL that
        /// directs to the company's privacy statement. Not required.</param>
        public MicrosoftgraphprivacyProfile(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string contactEmail = default(string), string statementUrl = default(string))
        {
            AdditionalProperties = additionalProperties;
            ContactEmail = contactEmail;
            StatementUrl = statementUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets a valid smtp email address for the privacy statement
        /// contact. Not required.
        /// </summary>
        [JsonProperty(PropertyName = "contactEmail")]
        public string ContactEmail { get; set; }

        /// <summary>
        /// Gets or sets a valid URL format that begins with http:// or
        /// https://. Maximum length is 255 characters. The URL that directs to
        /// the company's privacy statement. Not required.
        /// </summary>
        [JsonProperty(PropertyName = "statementUrl")]
        public string StatementUrl { get; set; }

    }
}
