// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Identity.DirectoryManagement.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MicrosoftgraphadministrativeUnit : MicrosoftgraphdirectoryObject
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphadministrativeUnit
        /// class.
        /// </summary>
        public MicrosoftgraphadministrativeUnit()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphadministrativeUnit
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">The unique idenfier for an entity.
        /// Read-only.</param>
        /// <param name="deletedDateTime">Date and time when this object was
        /// deleted. Always null when the object hasn't been deleted.</param>
        /// <param name="description">An optional description for the
        /// administrative unit. Supports $filter (eq, ne, in, startsWith),
        /// $search.</param>
        /// <param name="displayName">Display name for the administrative unit.
        /// Supports $filter (eq, ne, not, ge, le, in, startsWith, and eq on
        /// null values), $search, and $orderBy.</param>
        /// <param name="extensions">The collection of open extensions defined
        /// for this administrative unit. Nullable.</param>
        /// <param name="members">Users and groups that are members of this
        /// administrative unit. Supports $expand.</param>
        /// <param name="scopedRoleMembers">Scoped-role members of this
        /// administrative unit.</param>
        /// <param name="visibility">Controls whether the administrative unit
        /// and its members are hidden or public. Can be set to
        /// HiddenMembership. If not set (value is null), the default behavior
        /// is public. When set to HiddenMembership, only members of the
        /// administrative unit can list other members of the administrative
        /// unit.</param>
        public MicrosoftgraphadministrativeUnit(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string id = default(string), System.DateTime? deletedDateTime = default(System.DateTime?), string description = default(string), string displayName = default(string), IList<Microsoftgraphextension> extensions = default(IList<Microsoftgraphextension>), IList<MicrosoftgraphdirectoryObject> members = default(IList<MicrosoftgraphdirectoryObject>), IList<MicrosoftgraphscopedRoleMembership> scopedRoleMembers = default(IList<MicrosoftgraphscopedRoleMembership>), string visibility = default(string))
            : base(additionalProperties, id, deletedDateTime)
        {
            Description = description;
            DisplayName = displayName;
            Extensions = extensions;
            Members = members;
            ScopedRoleMembers = scopedRoleMembers;
            Visibility = visibility;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an optional description for the administrative unit.
        /// Supports $filter (eq, ne, in, startsWith), $search.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets display name for the administrative unit. Supports
        /// $filter (eq, ne, not, ge, le, in, startsWith, and eq on null
        /// values), $search, and $orderBy.
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the collection of open extensions defined for this
        /// administrative unit. Nullable.
        /// </summary>
        [JsonProperty(PropertyName = "extensions")]
        public IList<Microsoftgraphextension> Extensions { get; set; }

        /// <summary>
        /// Gets or sets users and groups that are members of this
        /// administrative unit. Supports $expand.
        /// </summary>
        [JsonProperty(PropertyName = "members")]
        public IList<MicrosoftgraphdirectoryObject> Members { get; set; }

        /// <summary>
        /// Gets or sets scoped-role members of this administrative unit.
        /// </summary>
        [JsonProperty(PropertyName = "scopedRoleMembers")]
        public IList<MicrosoftgraphscopedRoleMembership> ScopedRoleMembers { get; set; }

        /// <summary>
        /// Gets or sets controls whether the administrative unit and its
        /// members are hidden or public. Can be set to HiddenMembership. If
        /// not set (value is null), the default behavior is public. When set
        /// to HiddenMembership, only members of the administrative unit can
        /// list other members of the administrative unit.
        /// </summary>
        [JsonProperty(PropertyName = "visibility")]
        public string Visibility { get; set; }
    }
}
