// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.MicrosoftGraph.Applications.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// webApplication
    /// </summary>
    public partial class MicrosoftgraphwebApplication
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphwebApplication
        /// class.
        /// </summary>
        public MicrosoftgraphwebApplication()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphwebApplication
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="homePageUrl">Home page or landing page of the
        /// application.</param>
        /// <param name="logoutUrl">Specifies the URL that will be used by
        /// Microsoft's authorization service to logout an user using
        /// front-channel, back-channel or SAML logout protocols.</param>
        /// <param name="redirectUris">Specifies the URLs where user tokens are
        /// sent for sign-in, or the redirect URIs where OAuth 2.0
        /// authorization codes and access tokens are sent.</param>
        public MicrosoftgraphwebApplication(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string homePageUrl = default(string), MicrosoftgraphimplicitGrantSettings implicitGrantSettings = default(MicrosoftgraphimplicitGrantSettings), string logoutUrl = default(string), IList<string> redirectUris = default(IList<string>))
        {
            AdditionalProperties = additionalProperties;
            HomePageUrl = homePageUrl;
            ImplicitGrantSettings = implicitGrantSettings;
            LogoutUrl = logoutUrl;
            RedirectUris = redirectUris;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets home page or landing page of the application.
        /// </summary>
        [JsonProperty(PropertyName = "homePageUrl")]
        public string HomePageUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "implicitGrantSettings")]
        public MicrosoftgraphimplicitGrantSettings ImplicitGrantSettings { get; set; }

        /// <summary>
        /// Gets or sets specifies the URL that will be used by Microsoft's
        /// authorization service to logout an user using front-channel,
        /// back-channel or SAML logout protocols.
        /// </summary>
        [JsonProperty(PropertyName = "logoutUrl")]
        public string LogoutUrl { get; set; }

        /// <summary>
        /// Gets or sets specifies the URLs where user tokens are sent for
        /// sign-in, or the redirect URIs where OAuth 2.0 authorization codes
        /// and access tokens are sent.
        /// </summary>
        [JsonProperty(PropertyName = "redirectUris")]
        public IList<string> RedirectUris { get; set; }

    }
}
