// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.MicrosoftGraph.Applications.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// parentalControlSettings
    /// </summary>
    public partial class MicrosoftgraphparentalControlSettings
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphparentalControlSettings class.
        /// </summary>
        public MicrosoftgraphparentalControlSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphparentalControlSettings class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="countriesBlockedForMinors">Specifies the two-letter
        /// ISO country codes. Access to the application will be blocked for
        /// minors from the countries specified in this list.</param>
        /// <param name="legalAgeGroupRule">Specifies the legal age group rule
        /// that applies to users of the app. Can be set to one of the
        /// following values: ValueDescriptionAllowDefault. Enforces the legal
        /// minimum. This means parental consent is required for minors in the
        /// European Union and Korea.RequireConsentForPrivacyServicesEnforces
        /// the user to specify date of birth to comply with COPPA rules.
        /// RequireConsentForMinorsRequires parental consent for ages below 18,
        /// regardless of country minor rules.RequireConsentForKidsRequires
        /// parental consent for ages below 14, regardless of country minor
        /// rules.BlockMinorsBlocks minors from using the app.</param>
        public MicrosoftgraphparentalControlSettings(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), IList<string> countriesBlockedForMinors = default(IList<string>), string legalAgeGroupRule = default(string))
        {
            AdditionalProperties = additionalProperties;
            CountriesBlockedForMinors = countriesBlockedForMinors;
            LegalAgeGroupRule = legalAgeGroupRule;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets specifies the two-letter ISO country codes. Access to
        /// the application will be blocked for minors from the countries
        /// specified in this list.
        /// </summary>
        [JsonProperty(PropertyName = "countriesBlockedForMinors")]
        public IList<string> CountriesBlockedForMinors { get; set; }

        /// <summary>
        /// Gets or sets specifies the legal age group rule that applies to
        /// users of the app. Can be set to one of the following values:
        /// ValueDescriptionAllowDefault. Enforces the legal minimum. This
        /// means parental consent is required for minors in the European Union
        /// and Korea.RequireConsentForPrivacyServicesEnforces the user to
        /// specify date of birth to comply with COPPA rules.
        /// RequireConsentForMinorsRequires parental consent for ages below 18,
        /// regardless of country minor rules.RequireConsentForKidsRequires
        /// parental consent for ages below 14, regardless of country minor
        /// rules.BlockMinorsBlocks minors from using the app.
        /// </summary>
        [JsonProperty(PropertyName = "legalAgeGroupRule")]
        public string LegalAgeGroupRule { get; set; }

    }
}
