// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.MicrosoftGraph.Applications.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// preAuthorizedApplication
    /// </summary>
    public partial class MicrosoftgraphpreAuthorizedApplication
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphpreAuthorizedApplication class.
        /// </summary>
        public MicrosoftgraphpreAuthorizedApplication()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphpreAuthorizedApplication class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="appId">The unique identifier for the
        /// application.</param>
        /// <param name="delegatedPermissionIds">The unique identifier for the
        /// oauth2PermissionScopes the application requires.</param>
        public MicrosoftgraphpreAuthorizedApplication(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string appId = default(string), IList<string> delegatedPermissionIds = default(IList<string>))
        {
            AdditionalProperties = additionalProperties;
            AppId = appId;
            DelegatedPermissionIds = delegatedPermissionIds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the application.
        /// </summary>
        [JsonProperty(PropertyName = "appId")]
        public string AppId { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the oauth2PermissionScopes
        /// the application requires.
        /// </summary>
        [JsonProperty(PropertyName = "delegatedPermissionIds")]
        public IList<string> DelegatedPermissionIds { get; set; }

    }
}
