// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.MicrosoftGraph.Applications.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// informationalUrl
    /// </summary>
    public partial class MicrosoftgraphinformationalUrl
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphinformationalUrl
        /// class.
        /// </summary>
        public MicrosoftgraphinformationalUrl()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphinformationalUrl
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="logoUrl">CDN URL to the application's logo,
        /// Read-only.</param>
        /// <param name="marketingUrl">Link to the application's marketing
        /// page. For example, https://www.contoso.com/app/marketing</param>
        /// <param name="privacyStatementUrl">Link to the application's privacy
        /// statement. For example, https://www.contoso.com/app/privacy</param>
        /// <param name="supportUrl">Link to the application's support page.
        /// For example, https://www.contoso.com/app/support</param>
        /// <param name="termsOfServiceUrl">Link to the application's terms of
        /// service statement. For example,
        /// https://www.contoso.com/app/termsofservice</param>
        public MicrosoftgraphinformationalUrl(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), string logoUrl = default(string), string marketingUrl = default(string), string privacyStatementUrl = default(string), string supportUrl = default(string), string termsOfServiceUrl = default(string))
        {
            AdditionalProperties = additionalProperties;
            LogoUrl = logoUrl;
            MarketingUrl = marketingUrl;
            PrivacyStatementUrl = privacyStatementUrl;
            SupportUrl = supportUrl;
            TermsOfServiceUrl = termsOfServiceUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets CDN URL to the application's logo, Read-only.
        /// </summary>
        [JsonProperty(PropertyName = "logoUrl")]
        public string LogoUrl { get; set; }

        /// <summary>
        /// Gets or sets link to the application's marketing page. For example,
        /// https://www.contoso.com/app/marketing
        /// </summary>
        [JsonProperty(PropertyName = "marketingUrl")]
        public string MarketingUrl { get; set; }

        /// <summary>
        /// Gets or sets link to the application's privacy statement. For
        /// example, https://www.contoso.com/app/privacy
        /// </summary>
        [JsonProperty(PropertyName = "privacyStatementUrl")]
        public string PrivacyStatementUrl { get; set; }

        /// <summary>
        /// Gets or sets link to the application's support page. For example,
        /// https://www.contoso.com/app/support
        /// </summary>
        [JsonProperty(PropertyName = "supportUrl")]
        public string SupportUrl { get; set; }

        /// <summary>
        /// Gets or sets link to the application's terms of service statement.
        /// For example, https://www.contoso.com/app/termsofservice
        /// </summary>
        [JsonProperty(PropertyName = "termsOfServiceUrl")]
        public string TermsOfServiceUrl { get; set; }

    }
}
