// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.MicrosoftGraph.Applications.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// applicationServicePrincipal
    /// </summary>
    public partial class MicrosoftgraphapplicationServicePrincipal
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphapplicationServicePrincipal class.
        /// </summary>
        public MicrosoftgraphapplicationServicePrincipal()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftgraphapplicationServicePrincipal class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        public MicrosoftgraphapplicationServicePrincipal(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), Microsoftgraphapplication application = default(Microsoftgraphapplication), MicrosoftgraphservicePrincipal servicePrincipal = default(MicrosoftgraphservicePrincipal))
        {
            AdditionalProperties = additionalProperties;
            Application = application;
            ServicePrincipal = servicePrincipal;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "application")]
        public Microsoftgraphapplication Application { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "servicePrincipal")]
        public MicrosoftgraphservicePrincipal ServicePrincipal { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Application != null)
            {
                Application.Validate();
            }
        }
    }
}
