// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Cmdlets.MicrosoftGraph.Applications.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// resourceAccess
    /// </summary>
    public partial class MicrosoftgraphresourceAccess
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphresourceAccess
        /// class.
        /// </summary>
        public MicrosoftgraphresourceAccess()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftgraphresourceAccess
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="id">The unique identifier for one of the
        /// oauth2PermissionScopes or appRole instances that the resource
        /// application exposes.</param>
        /// <param name="type">Specifies whether the id property references an
        /// oauth2PermissionScopes or an appRole. Possible values are Scope or
        /// Role.</param>
        public MicrosoftgraphresourceAccess(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), System.Guid? id = default(System.Guid?), string type = default(string))
        {
            AdditionalProperties = additionalProperties;
            Id = id;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unmatched properties from the message are deserialized
        /// this collection
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for one of the
        /// oauth2PermissionScopes or appRole instances that the resource
        /// application exposes.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// Gets or sets specifies whether the id property references an
        /// oauth2PermissionScopes or an appRole. Possible values are Scope or
        /// Role.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
