trigger:
- main

pool:
  name: pool-windows-2019

steps:
- task: UseDotNet@2
  displayName: 'Pin .Net SDK 8.x'
  inputs:
    version: 8.x

- task: DotNetCoreCLI@2
  displayName: 'Build Debug'
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /p:Configuration=Debug /t:Build /NoLogo'

- task: PublishPipelineArtifact@0
  displayName: 'Save test results [preview]'
  inputs:
    artifactName: 'test-results'
    targetPath: 'artifacts\Test'
  condition: succeededOrFailed()
